"""
Pulse IQ race-intelligence dashboard output.

Reads race-level market intelligence generated by:

    py -m app.modules.race_intelligence.signals
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Optional

from app.modules.race_intelligence.models import (
    SignalTier,
    enrich_signals,
    signal_tier_summary,
)
from app.modules.race_intelligence.signals import signal_summary


RACE_INTELLIGENCE_DIR = Path(
    "data/horses/race_market_intelligence"
)

DEFAULT_RECORD_LIMIT = 100
DEFAULT_SIGNAL_LIMIT = 250


def clean(value: Any) -> str:
    return str(value or "").strip()


def safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def safe_float(value: Any) -> Optional[float]:
    try:
        if value is None:
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def parse_datetime(value: Any) -> Optional[datetime]:
    text = clean(value)

    if not text:
        return None

    if text.endswith("Z"):
        text = text[:-1] + "+00:00"

    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)

    return parsed.astimezone(timezone.utc)


def iter_jsonl_records(path: Path):
    try:
        with path.open("r", encoding="utf-8") as file_handle:
            for line_number, line in enumerate(
                file_handle,
                start=1,
            ):
                line = line.strip()

                if not line:
                    continue

                try:
                    record = json.loads(line)
                except json.JSONDecodeError as exc:
                    print(
                        "Skipping invalid race-intelligence "
                        f"JSONL line | {path} | "
                        f"line {line_number} | {exc}"
                    )
                    continue

                if isinstance(record, dict):
                    yield record

    except OSError as exc:
        print(
            "Unable to read race-intelligence "
            f"file {path}: {exc}"
        )


def load_race_intelligence_records(
    directory: Path = RACE_INTELLIGENCE_DIR,
) -> list[dict[str, Any]]:
    if not directory.exists():
        return []

    latest_by_race = {}

    for path in sorted(directory.glob("*.jsonl")):
        for record in iter_jsonl_records(path):
            race_key = clean(record.get("race_key"))
            race_key = race_key or clean(record.get("url"))

            if not race_key:
                continue

            existing = latest_by_race.get(race_key)

            if existing is None:
                latest_by_race[race_key] = record
                continue

            existing_time = parse_datetime(
                existing.get("generated_at")
            )
            record_time = parse_datetime(
                record.get("generated_at")
            )

            if (
                record_time is not None
                and (
                    existing_time is None
                    or record_time >= existing_time
                )
            ):
                latest_by_race[race_key] = record

    records = list(latest_by_race.values())

    records.sort(
        key=lambda record: (
            parse_datetime(record.get("latest_seen_at"))
            or datetime.min.replace(tzinfo=timezone.utc)
        ),
        reverse=True,
    )

    return records


def signal_sort_key(signal: dict[str, Any]):
    return (
        safe_float(signal.get("priority_score")) or 0,
        abs(safe_float(signal.get("impact")) or 0),
        abs(safe_float(signal.get("movement_pct")) or 0),
    )


def flatten_signals(
    records: Iterable[dict[str, Any]],
) -> list[dict[str, Any]]:
    flattened = []

    for record in records:
        race_key = clean(record.get("race_key"))

        for signal in record.get("signals", []):
            if not isinstance(signal, dict):
                continue

            enriched = dict(signal)
            enriched.setdefault("race_key", race_key)
            enriched.setdefault("url", record.get("url"))
            enriched.setdefault("course", record.get("course"))
            enriched.setdefault(
                "race_time",
                record.get("race_time"),
            )
            enriched["latest_seen_at"] = record.get(
                "latest_seen_at"
            )

            flattened.append(enriched)

    return enrich_signals(flattened)


def filter_records(
    records: Iterable[dict[str, Any]],
    course: Optional[str] = None,
    race_time: Optional[str] = None,
) -> list[dict[str, Any]]:
    target_course = clean(course).lower()
    target_time = clean(race_time).lower()

    filtered = []

    for record in records:
        if (
            target_course
            and clean(record.get("course")).lower()
            != target_course
        ):
            continue

        if (
            target_time
            and clean(record.get("race_time")).lower()
            != target_time
        ):
            continue

        filtered.append(record)

    return filtered


def filter_signals(
    signals: Iterable[dict[str, Any]],
    signal_type: Optional[str] = None,
    severity: Optional[str] = None,
    tier: Optional[str] = None,
    minimum_impact: Optional[float] = None,
    include_low_value: bool = False,
) -> list[dict[str, Any]]:
    target_type = clean(signal_type).lower()
    target_severity = clean(severity).upper()
    target_tier = clean(tier).upper()

    filtered = []

    for signal in signals:
        current_tier = clean(signal.get("tier")).upper()

        if (
            not include_low_value
            and current_tier == SignalTier.LOW_VALUE.value
        ):
            continue

        if (
            target_type
            and clean(signal.get("type")).lower()
            != target_type
        ):
            continue

        if (
            target_severity
            and clean(signal.get("severity")).upper()
            != target_severity
        ):
            continue

        if target_tier and current_tier != target_tier:
            continue

        impact = safe_float(signal.get("impact")) or 0

        if (
            minimum_impact is not None
            and abs(impact) < minimum_impact
        ):
            continue

        filtered.append(signal)

    filtered.sort(key=signal_sort_key, reverse=True)
    return filtered


def count_signal_types(
    signals: Iterable[dict[str, Any]],
) -> dict[str, int]:
    counts = {}

    for signal in signals:
        signal_type = clean(signal.get("type")) or "unknown"
        counts[signal_type] = counts.get(signal_type, 0) + 1

    return dict(
        sorted(
            counts.items(),
            key=lambda item: (-item[1], item[0]),
        )
    )


def count_severities(
    signals: Iterable[dict[str, Any]],
) -> dict[str, int]:
    counts = {
        "CRITICAL": 0,
        "HIGH": 0,
        "WARNING": 0,
        "INFO": 0,
    }

    for signal in signals:
        severity = (
            clean(signal.get("severity")).upper()
            or "INFO"
        )
        counts[severity] = counts.get(severity, 0) + 1

    return counts


def build_race_cards(
    records: Iterable[dict[str, Any]],
    globally_ranked_signals: Iterable[dict[str, Any]],
    include_low_value: bool = False,
) -> list[dict[str, Any]]:
    signals_by_race = {}

    for signal in globally_ranked_signals:
        race_key = clean(signal.get("race_key"))
        signals_by_race.setdefault(race_key, []).append(signal)

    cards = []

    for record in records:
        race_key = clean(record.get("race_key"))
        all_signals = signals_by_race.get(race_key, [])

        visible_signals = [
            signal
            for signal in all_signals
            if (
                include_low_value
                or signal.get("tier")
                != SignalTier.LOW_VALUE.value
            )
        ]

        top_signal = (
            visible_signals[0]
            if visible_signals
            else None
        )

        tier_counts = signal_tier_summary(
            all_signals,
            preserve_existing_tiers=True,
        )

        cards.append(
            {
                "race_key": record.get("race_key"),
                "url": record.get("url"),
                "course": record.get("course"),
                "race_time": record.get("race_time"),
                "runner_count": safe_int(
                    record.get("runner_count")
                ),
                "latest_seen_at": record.get(
                    "latest_seen_at"
                ),
                "signals": visible_signals,
                "signal_count": len(visible_signals),
                "raw_signal_count": len(all_signals),
                "hidden_low_value_count": tier_counts.get(
                    SignalTier.LOW_VALUE.value,
                    0,
                ),
                "tier_summary": tier_counts,
                "summary": signal_summary(visible_signals),
                "top_signal": top_signal,
                "top_tier": (
                    top_signal.get("tier")
                    if top_signal
                    else None
                ),
                "highest_priority_score": (
                    top_signal.get("priority_score")
                    if top_signal
                    else 0
                ),
                "has_warning": any(
                    clean(signal.get("severity")).upper()
                    in (
                        "WARNING",
                        "HIGH",
                        "CRITICAL",
                    )
                    for signal in visible_signals
                ),
                "has_elite_signal": any(
                    signal.get("tier")
                    == SignalTier.ELITE.value
                    for signal in visible_signals
                ),
                "has_strong_signal": any(
                    signal.get("tier")
                    == SignalTier.STRONG.value
                    for signal in visible_signals
                ),
            }
        )

    cards.sort(
        key=lambda card: (
            card["has_elite_signal"],
            card["has_strong_signal"],
            safe_float(
                card.get("highest_priority_score")
            )
            or 0,
            card["signal_count"],
            parse_datetime(card.get("latest_seen_at"))
            or datetime.min.replace(tzinfo=timezone.utc),
        ),
        reverse=True,
    )

    return cards


def get_race_intelligence_dashboard(
    course: Optional[str] = None,
    race_time: Optional[str] = None,
    signal_type: Optional[str] = None,
    severity: Optional[str] = None,
    tier: Optional[str] = None,
    minimum_impact: Optional[float] = None,
    include_low_value: bool = False,
    record_limit: int = DEFAULT_RECORD_LIMIT,
    signal_limit: int = DEFAULT_SIGNAL_LIMIT,
):
    all_records = load_race_intelligence_records()

    records = filter_records(
        all_records,
        course=course,
        race_time=race_time,
    )

    all_signals = flatten_signals(records)

    filtered_signals = filter_signals(
        all_signals,
        signal_type=signal_type,
        severity=severity,
        tier=tier,
        minimum_impact=minimum_impact,
        include_low_value=include_low_value,
    )

    safe_record_limit = max(
        1,
        safe_int(record_limit, DEFAULT_RECORD_LIMIT),
    )
    safe_signal_limit = max(
        1,
        safe_int(signal_limit, DEFAULT_SIGNAL_LIMIT),
    )

    visible_records = records[:safe_record_limit]
    visible_signals = filtered_signals[:safe_signal_limit]

    cards = build_race_cards(
        visible_records,
        all_signals,
        include_low_value=include_low_value,
    )

    all_tier_counts = signal_tier_summary(
        all_signals,
        preserve_existing_tiers=True,
    )
    visible_tier_counts = signal_tier_summary(
        filtered_signals,
        preserve_existing_tiers=True,
    )

    summary = signal_summary(filtered_signals)
    summary.update(
        {
            "races": len(records),
            "visible_races": len(visible_records),
            "raw_signals": len(all_signals),
            "actionable_signals": len(filtered_signals),
            "visible_signals": len(visible_signals),
            "hidden_low_value": (
                all_tier_counts.get(
                    SignalTier.LOW_VALUE.value,
                    0,
                )
                if not include_low_value
                else 0
            ),
            "elite_signals": visible_tier_counts.get(
                SignalTier.ELITE.value,
                0,
            ),
            "strong_signals": visible_tier_counts.get(
                SignalTier.STRONG.value,
                0,
            ),
            "watch_signals": visible_tier_counts.get(
                SignalTier.WATCH.value,
                0,
            ),
            "steamers": sum(
                1
                for signal in filtered_signals
                if signal.get("type")
                == "biggest_steamer"
            ),
            "drifters": sum(
                1
                for signal in filtered_signals
                if signal.get("type")
                == "biggest_drifter"
            ),
            "volatile_runners": sum(
                1
                for signal in filtered_signals
                if signal.get("type")
                == "most_volatile_runner"
            ),
        }
    )

    latest_values = [
        parse_datetime(record.get("latest_seen_at"))
        for record in records
    ]
    latest_values = [
        value
        for value in latest_values
        if value is not None
    ]
    latest_update = (
        max(latest_values).isoformat()
        if latest_values
        else None
    )

    available_courses = sorted(
        {
            clean(record.get("course"))
            for record in all_records
            if clean(record.get("course"))
        }
    )

    return {
        "signals": visible_signals,
        "all_signal_count": len(filtered_signals),
        "raw_signal_count": len(all_signals),
        "hidden_low_value_count": summary[
            "hidden_low_value"
        ],
        "summary": summary,
        "tier_summary": visible_tier_counts,
        "all_tier_summary": all_tier_counts,
        "signal_type_counts": count_signal_types(
            filtered_signals
        ),
        "severity_counts": count_severities(
            filtered_signals
        ),
        "races": cards,
        "race_count": len(records),
        "latest_update": latest_update,
        "available_courses": available_courses,
        "available_tiers": [
            SignalTier.ELITE.value,
            SignalTier.STRONG.value,
            SignalTier.WATCH.value,
            SignalTier.LOW_VALUE.value,
        ],
        "filters": {
            "course": course,
            "race_time": race_time,
            "signal_type": signal_type,
            "severity": severity,
            "tier": tier,
            "minimum_impact": minimum_impact,
            "include_low_value": include_low_value,
        },
        "status": "READY" if records else "NO_DATA",
        "source_directory": str(
            RACE_INTELLIGENCE_DIR
        ),
    }


if __name__ == "__main__":
    dashboard = get_race_intelligence_dashboard()

    print("=" * 70)
    print("PULSE RACE INTELLIGENCE DASHBOARD OUTPUT")
    print("=" * 70)
    print(f"Status: {dashboard['status']}")
    print(f"Races: {dashboard['race_count']}")
    print(
        "Raw signals: "
        f"{dashboard['raw_signal_count']}"
    )
    print(
        "Actionable signals: "
        f"{dashboard['all_signal_count']}"
    )
    print(
        "Hidden low-value: "
        f"{dashboard['hidden_low_value_count']}"
    )
    print(
        "Elite: "
        f"{dashboard['tier_summary']['ELITE']}"
    )
    print(
        "Strong: "
        f"{dashboard['tier_summary']['STRONG']}"
    )
    print(
        "Watch: "
        f"{dashboard['tier_summary']['WATCH']}"
    )
    print(
        "Warnings: "
        f"{dashboard['summary']['warnings']}"
    )
    print(
        "Latest update: "
        f"{dashboard['latest_update']}"
    )
    print("=" * 70)